// Bracketing Instructions, from G. K. Beale's Exegetical Manual: Scott
// Hafemann's "The Method Behind My Madness" (his summary of Daniel Fuller's
// logical relationships and bracket symbols), "Discourse Analysis in a
// Nutshell", and "Hints for Doing Logical Relationships (revised)". The
// wording follows the source closely; only OCR errors, typography and
// reference style have been corrected.
// Block format and inline markup: see INSTRUCTIONS_STYLE_SHEET.md.
// The web tool (../index.html) carries an identical copy of this array.

import type { TextFlowBlock } from "./textFlowInstructions";

export const BRACKETING_SOURCE = "Daniel Fuller and Gregory Beale";

export const BRACKETING_INSTRUCTIONS: TextFlowBlock[] = [
	{ h: "1. Discourse Analysis" },
	{ indent: true, p: "Most students of the Bible do not know how to read (= exegete) for understanding. Instead they merely read for information, gladly pouncing upon an author, holding him or her up with their well-trained eye, and then robbing the text of its conclusions. But although their minds become filled with many stolen treasures, they never fool anyone. Everyone knows they are thieves and can be exposed at any time with a good question. The owner’s conclusions have merely become the thief’s opinions. And such stealing is wrong, even when the opinions in view are biblical opinions." },
	{ indent: true, p: "Discourse analysis is designed to help us become “honest” readers who desire to understand rather than steal. The two best teachers I have ever had both taught me that to understand (our goal in exegesis) involves thinking an author’s thoughts after him or her. Or to put it another way, the goal of reading the Bible is to be able to restate an author’s original intention in such a way that if the author were listening he or she would agree. The goal is to see reality through another person’s eyes. But this is simply impossible until one has thought his or her way, step by step, after the author." },
	{ indent: true, p: "This is where the art and skill of discourse analysis fits in. In discourse analysis we do not attempt to put the author’s words into our own; rather, we simply attempt to isolate each proposition (the author’s “steps”) and to demonstrate how they relate to one another. Having done so, we then can trace the logical development of the author’s argument step by step by indicating how the flow of thought moves from logical level to logical level. Finally, after we have a flow chart of the author’s argument, we will be able to isolate each of the author’s main logical levels and gain an overview of the argument’s development. The result of our labor will be an understanding of the main point of a text and the ways in which it is supported. So discourse analysis has four distinct but related steps:" },
	{ marker: "1.", level: 1, li: "Separate out the individual propositions of the text." },
	{ marker: "2.", level: 1, li: "Determine the logical relationships between the propositions." },
	{ marker: "3.", level: 1, li: "Trace the flow of the argument from step to step." },
	{ marker: "4.", level: 1, li: "Organize the text into its major logical levels, thus establishing its main and supporting points." },

	{ h: "2. The Logical Relationships between Propositions" },
	{ indent: true, p: "The key to any discourse analysis is therefore the ability to separate a text into its constituent propositions and the art of determining their logical interrelationships. Unfortunately, many people do not know what a proposition is, nor what relationships are possible between them. The first gap is easy to fill. With some practice most people are able to recognize propositions in a text, and even become skilled enough to argue over when a certain prepositional or participial phrase ought to be considered to be one or not! By God’s grace, the second need has also met its match through the work of Dr. Daniel P. Fuller of Fuller Theological Seminary. Dr. Fuller has done a great service to us in our hermeneutical task by classifying these various relationships and providing us with a vocabulary with which we can talk about them. This material can be found in detail in his *Hermeneutics Syllabus* (Pasadena, CA, 1969). What follows is taken from that syllabus with his permission." },
	{ indent: true, p: "The relationships between propositions fall into two major classes: __Coordinate Relationships__ and __Subordinate Relationships__. Two clauses have a coordinate relationship if one does not support the other in some way, but each is independent and makes its own contribution to the whole. “I ate pickles for lunch and I studied for my Interp class” are two coordinate propositions. They do not support each other, but describe a series of things that I did. Each can stand independent of the other. On the other hand, a proposition has a subordinate relationship to another clause if it supports that clause in some way. For example: “I ate pickles because I had no money” is a compound sentence with two propositions. The second proposition, “because I had no money,” is subordinate to the first, providing its ground. “I ate pickles” is thus the main point of this text. ***The main point of a text is that proposition which is supported by all the other propositions and which itself does not support any other.***" },
	{ indent: true, p: "There are a number of subclasses under each of these major classes, and each of these, together with the typical conjunctions used to indicate them, must be mastered." },

	{ marker: "I.", level: 0, li: "**Coordinate Relationships between Propositions** (non-supportive)" },
	{ marker: "A.", level: 1, li: "**Series:** the relationship between propositions, each of which makes its independent contribution to the whole." },
	{ level: 1, p: "*Typical conjunctions:* and, moreover, furthermore, likewise (and many more)." },
	{ level: 1, p: "*Example:* “Every one who asks receives, and he who seeks finds, and to him who knocks it will be opened” (Matt 7:8)." },
	{ marker: "B.", level: 1, li: "**Progression:** like a series, but each proposition is a further step toward a climax." },
	{ level: 1, p: "*Conjunctions:* then (plus others like those under “Series”)." },
	{ level: 1, p: "*Example:* “Those whom he predestined he called; and those whom he called he also justified; and those whom he justified he also glorified” (Rom 8:30)." },
	{ marker: "C.", level: 1, li: "**Alternative:** each proposition expresses an opposite possibility arising from a situation." },
	{ level: 1, p: "*Conjunctions:* but, on the other hand, while, etc." },
	{ level: 1, p: "*Example:* “Some were convinced while others disbelieved” (Acts 28:24)." },

	{ marker: "II.", level: 0, li: "**Subordinate Relationships between Propositions** (supportive)" },
	{ marker: "A.", level: 1, li: "**Support by Restatement**" },
	{ marker: "a.", level: 2, li: "**Way-End** (modal clause – main clause): the relationship between a statement of an action (end) and one which tells more explicitly what is involved in carrying out this action (way)." },
	{ level: 2, p: "*Conjunctions:* in that, by, etc." },
	{ level: 2, p: "*Example:* “God left not himself without a witness, in that he gave you from heaven rains and fruitful seasons” (Acts 14:17). (We speak of the second proposition “supporting” the first here because it is not independent of it but stands in the service of the first proposition, spelling out in more detail the “way” God gave witness.)" },
	{ marker: "b.", level: 2, li: "**Comparison:** the relationship between a statement expressing an action and one making that action clearer by showing what it is like." },
	{ level: 2, p: "*Conjunctions:* even as, as … so, etc." },
	{ level: 2, p: "*Example:* “As my Father has sent me, so send I you” (John 20:21)." },
	{ marker: "c.", level: 2, li: "**Negative-Positive:** the relationship between two alternatives, one of which is denied so that the other is enforced. It is also the relationship implicit in contrasting statements." },
	{ level: 2, p: "*Conjunctions:* not … but, etc." },
	{ level: 2, p: "*Example:* “Do not be foolish, but understand what the will of the Lord is” (Eph 5:17; cf. 1 Cor 4:10 for an example of contrast)." },
	{ marker: "d.", level: 2, li: "**General-Specific:** the relationship between a proposition stating a whole and one or more propositions which set forth the parts of the whole." },
	{ level: 2, p: "*Example:* “Jacob supplanted me these two times; he took away my birthright and now he has taken away my blessing” (Gen 27:36; cf. 1 Cor 9:19–22)." },
	{ marker: "e.", level: 2, li: "**Fact-Interpretation:** the relationship between an original statement and one clarifying its meaning. The interpreting proposition might define only one word of a preceding proposition. It differs from “General-Specific” in that the interpreting proposition does not set forth a distinguishable part of the preceding whole." },
	{ level: 2, p: "*Example:* “And they drank of the rock that followed them, and the rock was Christ” (1 Cor 10:4; cf. 1 Cor 5:9–11)." },
	{ marker: "B.", level: 1, li: "**Support by Distinct Statement**" },
	{ marker: "a.", level: 2, li: "**Ground** (main clause – causal clause): the relationship between a statement and the argument or basis on which it stands. In this relationship the supporting proposition follows the supported one." },
	{ level: 2, p: "*Conjunctions:* for, because, since, etc." },
	{ level: 2, p: "*Example:* “Blessed are the poor in spirit, for theirs is the kingdom of heaven” (Matt 5:3; cf. Phil 2:25–26)." },
	{ marker: "b.", level: 2, li: "**Inference** (main clause – inferential clause): the only difference between this and the “Ground” relationship is that here the supporting proposition always precedes the supported one." },
	{ level: 2, p: "*Conjunctions:* therefore, wherefore, consequently, accordingly, etc." },
	{ level: 2, p: "*Example:* “The scribes and Pharisees sit in Moses’ seat. All these things therefore, whatever they bid you, these do and observe” (Matt 23:2–3; cf. 1 Pet 5:5b–6)." },
	{ marker: "c.", level: 2, li: "**Cause-Effect** (main clause – result clause): the relationship between an action and one automatically consequent upon that action." },
	{ level: 2, p: "*Conjunctions:* so … that; that; so that; etc." },
	{ level: 2, p: "*Example:* “God so loved the world that he gave his only begotten Son” (John 3:16)." },
	{ marker: "d.", level: 2, li: "**Conditional:** this is like the “Cause-Effect” relationship except that the existence of the cause is only potential." },
	{ level: 2, p: "*Conjunctions:* if … then; if; provided that; except; etc." },
	{ level: 2, p: "*Example:* “If you love me, keep my commandments” (John 14:15; cf. Gal 5:16)." },
	{ marker: "e.", level: 2, li: "**Means-End** (main clause – purpose clause): the relationship between an action and the one that is intended to come as a result." },
	{ level: 2, p: "*Conjunctions:* in order that; that; with a view to; to the end that; lest; etc." },
	{ level: 2, p: "*Example:* “I long to see you, that I might impart some spiritual gift to strengthen you” (Rom 1:11)." },
	{ marker: "f.", level: 2, li: "**Temporal:** the relationship between a proposition and the occasion (not quite the cause) when it can occur." },
	{ level: 2, p: "*Conjunctions:* when; whenever; etc." },
	{ level: 2, p: "*Examples:* “When you fast, do not look dismal” (Matt 6:16). “Blessed are you when men hate you” (Luke 6:22)." },
	{ marker: "g.", level: 2, li: "**Locative**" },
	{ marker: "C.", level: 1, li: "**Support by Contrary Statement**" },
	{ marker: "a.", level: 2, li: "**Adversative** (concessive clause – main clause): the relationship between a main clause that stands despite a contrary statement, and that contrary statement. The concessive clause “supports” the main clause because it highlights the strength of the main clause, which stands despite the obstacle of the concessive clause." },
	{ level: 2, p: "*Conjunctions:* although … yet; though; but; nevertheless; etc." },
	{ level: 2, p: "*Example:* “Though you have ten thousand instructors in Christ, yet you do not have many fathers” (1 Cor 4:15; cf. 1 Cor 9:13–15)." },
	{ marker: "b.", level: 2, li: "**Question-Answer:** this relationship is included here under “C” because, when the answer is opposite that implied or expected in the question, the question behaves like a concessive clause and the relationship is in reality adversative." },
	{ level: 2, p: "*Example:* “Shall we continue in sin that grace may abound? God forbid” (Rom 6:1–2)." },
	{ level: 2, p: "But when an answer contains no surprise, it functions like a restatement of the question." },
	{ level: 2, p: "*Example:* “What says the Scripture? Abraham believed God …” (Rom 4:3)." },
	{ marker: "c.", level: 2, li: "**Situation-Response:** this relationship is included here under “C” because when a person responds in a way not intended by the situation that another creates, the situation behaves like a concessive clause and the relationship is in reality adversative." },
	{ level: 2, p: "*Example:* “How often would I have gathered your children together as a hen gathers her brood under her wings, and you would not” (Matt 23:37; cf. Jer 25:4–7)." },
	{ level: 2, p: "But when the response accords with the situation that has been created, then “Situation-Response” behaves like “Cause-Effect.”" },
	{ level: 2, p: "*Example:* “I did one deed, and you all marvel at it” (John 7:21)." },

	{ h: "3. Abbreviations for the Relationships" },
	{ indent: true, p: "Most units of thought consist of a series of propositions which is too long and whose logical interrelationships are too complicated for us to hold them suspended in our minds. But in order to gain an overview of an author’s argument which is clear enough to allow serious interaction with the text, this is precisely what must be done. It thus becomes imperative that we have a way in which we can represent the flow of the argument in symbols so that complicated arguments can be easily followed. The following brackets and their symbols will enable us to accomplish this important task." },
	{ marker: "I.", level: 0, li: "Coordinate Relationships" },
	{ level: 1, sym: [
		{ marker: "A.", term: "Series", mid: "S", note: "S" },
		{ marker: "B.", term: "Progression", mid: "P", note: "P" },
		{ marker: "C.", term: "Alternative", mid: "A", note: "A" },
	] },
	{ marker: "II.", level: 0, li: "Subordinate Relationships" },
	{ marker: "A.", level: 1, li: "Support by Restatement" },
	{ level: 2, sym: [
		{ marker: "a.", term: "Way-End", top: "W", bot: "Ed", note: "W → Ed*" },
		{ marker: "b.", term: "Comparison", mid: "//", note: "// → *" },
		{ marker: "c.", term: "Negative-Positive", top: "−", bot: "+", note: "− → +*" },
		{ marker: "d.", term: "General-Specific", top: "Gn", bot: "Sp", note: "Gn → Sp*" },
		{ marker: "e.", term: "Fact-Interpretation", top: "Ft", bot: "In", note: "Ft → In*" },
	] },
	{ marker: "B.", level: 1, li: "Support by Distinct Statement" },
	{ level: 2, sym: [
		{ marker: "a.", term: "Ground", mid: "G", note: "G → *" },
		{ marker: "b.", term: "Inference", mid: "∴", note: "∴ → *" },
		{ marker: "c.", term: "Cause-Effect", top: "C", bot: "E", note: "C → E*" },
		{ marker: "d.", term: "Conditional", top: "C?", bot: "E", note: "C? → E*" },
		{ marker: "e.", term: "Means-End", top: "M", bot: "Ed", note: "M → Ed*" },
		{ marker: "f.", term: "Temporal", mid: "T", note: "T → *" },
		{ marker: "g.", term: "Locative", mid: "L", note: "L → *" },
	] },
	{ marker: "C.", level: 1, li: "Support by Contrary Statement" },
	{ level: 2, sym: [
		{ marker: "a.", term: "Adversative", mid: "Adv", note: "Adv → *" },
		{ marker: "b.", term: "Question-Answer", top: "Q", bot: "A", note: "Q → A*" },
		{ marker: "c.", term: "Situation-Response", top: "S", bot: "R", note: "S → R*" },
	] },
	{ indent: true, p: "**Memorize these classifications and their symbols.** Now we can begin to do the hard work of reading, a work so difficult (no “speed reading” is real reading!) that a sure sign you have done it will be fatigue. As Mortimer J. Adler put it, “Reading that is reading entails the most intense mental activity. If you are not tired out, you probably have not been doing the work. Far from being passive and relaxing, I have always found what little reading I have done the most arduous and active occupation” (*How to Read a Book*, 1940 ed., p. 110)." },

	{ h: "4. Tracing the Flow of the Argument" },
	{ indent: true, p: "Once we have mastered the various logical relationships that *can* exist between propositions, we will be able to discover and determine which relationships actually do exist as the author’s argument unfolds. Therefore, our first task in exegesis will be to analyze the discourse by tracing the flow of the argument. Specifically, we will" },
	{ marker: "a.", level: 1, li: "translate the passage from Greek into a literal English rendering;" },
	{ marker: "b.", level: 1, li: "then go through the passage isolating the individual propositions. Remember that each proposition must contain both a subject and a predicate. If you deem it necessary to make a participial or prepositional phrase into a separate proposition, you must either convert the participle into a finite verb or supply one for the prepositional phrase;" },
	{ marker: "c.", level: 1, li: "next, attempt to relate each proposition to what __precedes__; indicate your understanding of the argument by selecting a connecting word or phrase which makes each relationship explicit. Whenever an author supplies such a connecting link (conjunction or phrase), remain faithful to it unless it seems absolutely impossible to do so!" },
	{ marker: "d.", level: 1, li: "Finally, outline the argument in the margin by using the bracket method. When you are finished, you should be able to state the main point of the text and all of its supporting points." },

	{ h: "Discourse Analysis in a Nutshell" },
	{ marker: "1.", level: 0, li: "Make a literal English translation for your passage." },
	{ marker: "2.", level: 0, li: "Isolate the individual propositions (each with a subject and predicate) and place one proposition on each line (tab these lines over to about the center of the page)." },
	{ marker: "3.", level: 0, li: "Determine how each proposition relates to its preceding and following propositions (Cause-Effect, Ground, Inference, Comparison, etc.)." },
	{ marker: "4.", level: 0, li: "Insert a connecting word or phrase at the beginning of each line to make the logical relationship explicit." },
	{ marker: "a.", level: 1, li: "When the author supplies a connecting word, use this to help determine the relationship by determining the syntactical and lexical range of the word (e.g., the conjunction γάρ usually introduces a Ground statement; consult BDAG or Wallace’s grammar on such words)." },
	{ marker: "b.", level: 1, li: "Underline the connecting words or phrases at the start of each line." },
	{ marker: "5.", level: 0, li: "Trace the argument by inserting brackets in the left margin." },
	{ marker: "a.", level: 1, li: "Begin with the subordinate brackets, connecting the thoughts within the sub-units of the passage." },
	{ marker: "b.", level: 1, li: "Then connect the brackets between the sub-units to trace the larger arguments." },
	{ marker: "c.", level: 1, li: "How to connect brackets:" },
	{ marker: "i.", level: 2, li: "On each bracket, the end carrying the logical main point should be marked with an asterisk (except for Series, Progressions, Comparisons, etc.)." },
	{ marker: "ii.", level: 2, li: "Connect brackets by connecting the asterisks (with Series, etc., draw your bracket from the middle). Every bracket must be connected to another (never more than one)." },
	{ marker: "iii.", level: 2, li: "Never cross over lines when drawing brackets." },
	{ marker: "iv.", level: 2, li: "The outermost asterisk on your brackets should indicate the logical main point of the entire passage." },
	{ marker: "6.", level: 0, li: "Check to make sure that your connecting words or phrases match your D.A. brackets (e.g., an Inference must be indicated by a connecting word like “therefore”)." },
	{ marker: "7.", level: 0, li: "Based upon your D.A., write out a one-sentence exegetical idea for your passage. Then reformulate it into a one-sentence homiletical idea (the preaching idea)." },
	{ marker: "a.", level: 1, li: "Exegetical Idea" },
	{ marker: "i.", level: 2, li: "What is the author talking about? Formulate this as a question." },
	{ marker: "ii.", level: 2, li: "What is the author saying about what he is talking about? Formulate this as the answer to the question." },
	{ marker: "iii.", level: 2, li: "Then merge your question and answer by lopping off the interrogative. This is your exegetical idea." },
	{ marker: "b.", level: 1, li: "Homiletical Idea" },
	{ marker: "i.", level: 2, li: "Now take your exegetical idea and formulate it in a manner that is more directed towards your hearers (focusing upon application)." },
	{ marker: "ii.", level: 2, li: "This is the phrase that you will repeat over and over throughout your sermon." },
	{ marker: "iii.", level: 2, li: "As you move towards application, be aware of the various hermeneutical errors that can be committed even by seasoned exegetes: personalizing, universalizing, spiritualizing, allegorizing, exemplarizing, moralizing, etc." },

	{ h: "Hints for Doing Logical Relationships" },
	{ marker: "1)", level: 0, li: "Think in terms of sub-units within the argument." },
	{ marker: "a.", level: 1, li: "Too often it is too easy to just naturally try to relate one line to the following line, whether or not they are directly related in the flow of argument. The goal is not to relate one line to the next, but the component parts in the argument." },
	{ marker: "b.", level: 1, li: "Therefore look for logical connectors within the flow of the argument (i.e., “so that,” “because,” “for,” etc.), and then surmise whether a particular connector is conjoining thoughts WITHIN a particular sub-unit or BETWEEN sub-units in the flow of an argument. In this way you will see how the various building blocks within the argument are put together." },
	{ marker: "2)", level: 0, li: "Brackets are to be subordinate or superordinate." },
	{ marker: "a.", level: 1, li: "Inner brackets are subordinate (these are thoughts within sub-units)." },
	{ marker: "-", level: 2, li: "When the following proposition supports the preceding proposition, the bracket goes on the inside. (There may be exceptions.)" },
	{ marker: "b.", level: 1, li: "Outer brackets are superordinate (these are for connecting sub-units together)." },
	{ marker: "-", level: 2, li: "When the following proposition is supported by the preceding proposition, the bracket goes on the outside. (There may be exceptions.)" },
	{ marker: "c.", level: 1, li: "Brackets are NEVER to be crossed." },
	{ marker: "3)", level: 0, li: "Bracket off your asterisks; this is how you reflect the logical progression of the argument. That is to say, all asterisks must be “covered” by a Discourse Analysis bracket except that asterisk with which you are designating the main point of the passage." },
	{ marker: "4)", level: 0, li: "General Rules of D.A.:" },
	{ marker: "a.", level: 1, li: "Every bracket has a * (except S, some //, P, etc.)." },
	{ marker: "b.", level: 1, li: "Every bracket must be connected to another (no “hanging” brackets), and they are to be connected to the *’d end of that bracket (or the middle of the bracket if there is no *)." },
	{ marker: "c.", level: 1, li: "Brackets should connect propositions, not keywords. Keywords only help you identify the connection." },
	{ marker: "5)", level: 0, li: "General principles for your English translation:" },
	{ marker: "a.", level: 1, li: "Every logical relationship should be reflected in the translation." },
	{ marker: "1.", level: 2, li: "If you call something a Series, you must translate with “and”; do not assume it." },
	{ marker: "2.", level: 2, li: "If you call something a CE* but you translate with “after” or “when,” then you have not grasped what the D.A. is telling you." },
	{ marker: "3.", level: 2, li: "**This step is the evidence that you understand what you are doing.** Failure to do this correctly reveals a failure to understand the logical flow of the passage. If your logical analysis, translated into English, does not properly reflect the Greek passage, then you have not done Discourse Analysis correctly. Don’t fudge your translation; change your Discourse Analysis!!" },
	{ marker: "b.", level: 1, li: "Only underline Logical Relationship phrases (like *in order that*, etc.). No need to underline the pronoun or the tense of the participle; those items are carried in the Grammar, not the Logical Analysis." },
	{ marker: "c.", level: 1, li: "REPEAT: Every logical relationship should be reflected in your translation!" },
	{ marker: "6)", level: 0, li: "When doing a Translation Comparison:" },
	{ level: 1, p: "The point of this part of the assignment is to make you realize that the translators assume certain logical relationships between propositions when they translate. Your task is not to identify the different lexical issues, or the different ordering, or the different choice of pronouns, or the different phrasing, BUT the different Logical Relationship assumed by the translator! If one translates a participle with “after” and another translates the same participle with “because,” the difference is not in the Greek word or text! The difference is in the Discourse Analysis, which, ultimately, is an interpretation of the logical relationships between the propositions in a passage! This is intended to sharpen your skills at doing D.A., not merely an exercise in looking at six different translations." },
	{ p: "***Finally…*** When your logically related flow is complete, look to see that the asterisked unit of thought on the outermost bracket reflects what you believe to be the main point in the argument. If it does not, then your bracketing does not reflect your interpretation of the argument." },
];
