// Sentence Flow Instructions, from the "Sentence Flows" section of G. K.
// Beale's Exegetical Manual. The wording follows the source closely; only OCR
// errors, typography and reference style have been corrected. Block format
// and inline markup: see INSTRUCTIONS_STYLE_SHEET.md. The { sf } diagrams
// place each segment at an em offset measured from the source page, so
// modifiers sit under the word they modify, as in the original.
// The web tool (../index.html) carries an identical copy of this array.

import type { TextFlowBlock } from "./textFlowInstructions";

export const SENTENCE_FLOW_SOURCE = "Daniel Fuller and Gregory Beale";

export const SENTENCE_FLOW_INSTRUCTIONS: TextFlowBlock[] = [
	{ h: "Sentence Flows: Introduction" },
	{ indent: true, p: "The sentence flow is a visual way to understand the flow of thought or the grammar of a biblical text. In __exegetical__ courses one uses the flow more often to understand the flow of narrative (Gospels, Acts, Revelation) or rhetorical (Epistles) thought. In __language__ courses such as GL 201, however, we will use the flow to analyze grammar. The sentence flow as a visualization of grammar is superior to the sentence __diagram__, a slightly more wooden and fragmented approach which Brooks and Winbery use in their discussion of sentences and clauses in their *Syntax*. If you learn to use the flow with reflexive ease in your exegesis, you will find it more valuable than the diagram, since the flow better appreciates the design and purpose of language." },
	{ indent: true, p: "The flow operates in terms of two principles, __subordination__ and __coordination__. The first is more important than the second, so we will concentrate on subordination. There are at least three types of subordination which occur in texts:" },
	{ marker: "(1)", level: 1, li: "at the broadest level, whole blocks of material made up of several sentences can be subordinated to other blocks of material;" },
	{ marker: "(2)", level: 1, li: "more narrowly, we encounter the subordination of some (dependent, subordinate, or hypotactic) __clauses__ to the main (or independent) clause of a given sentence;" },
	{ marker: "(3)", level: 1, li: "more narrowly still, we encounter the subordination of some units __within a clause__ to other units in that same clause." },
	{ p: "The sentence flow is designed to visualize these types of subordination." },
	{ indent: true, p: "Since grammar largely functions in terms of the second and third types of subordination, we are more concerned in GL 201 with these two types, although in exegetical courses you will be concerned with all three. And of the second and third, the third will concern us more than the second, since we don’t get to clauses officially until the last part of the term." },

	{ h: "(1)" },
	{ indent: true, p: "Let us look at the most narrow type of subordination, that of the subordination of some units to others within a clause. Here we have two basic relationships expressed: that of __adjectives to nouns__, and that of __adverbs to verbs__. In other words, in a given clause you will have adjectival ideas subordinated to __noun-governors__, and adverbial ideas subordinated to __verb-governors__. In any clause there are no more than five chief governors: the subject, the verb, the direct object, the indirect object, and the predicate. Four of these (subject, direct object, predicate, and indirect object) are noun-governors; the remaining one (the verb) is a verb-governor. Thus in the following clause from John 5:14" },
	{ flow: ["μετὰ ταῦτα εὑρίσκει αὐτὸν ὁ Ἰησοῦς ἐν τῷ ἱερῷ"] },
	{ p: "we find __three__ chief governors: a subject (ὁ Ἰησοῦς), a verb (εὑρίσκει), and a direct object (αὐτόν). Thus the __top line__ of a sentence flow, which consists of the chief governors to which all else in a sentence will be subordinated, will be" },
	{ sf: [
		[{ x: 0, t: "ὁ Ἰησοῦς" }, { x: 7.3, t: "εὑρίσκει" }, { x: 13.5, t: "αὐτόν" }],
	] },
	{ indent: true, p: "For this sentence we don’t have to worry about an indirect object or a predicate (the two other chief governors in a sentence), since neither appears in the sentence. Note that the word order has been rearranged to follow English word order: subject, verb, predicate, direct object, and indirect object. The rearrangement helps us to identify the grammatical role of each of the three chief governors in this sentence." },
	{ indent: true, p: "What do we do with the remaining material in John 5:14? Since the remainder is not subject, verb, direct object, indirect object, or predicate, we must __subordinate__ it. Since we said that the two basic relationships in a clause are between adjective and noun and between adverb and verb, then the remaining material will either be adjectival material subordinated to a governing noun, or adverbial material subordinated to a governing verb. In John 5:14, the remainder, consisting of two prepositional phrases, should be subordinated to the verb, since as a rule most prepositional phrases are adverbial. Thus we will flow the sentence as" },
	{ sf: [
		[{ x: 0, t: "ὁ Ἰησοῦς" }, { x: 7.3, t: "~~εὑρίσκει~~" }, { x: 13.5, t: "αὐτόν" }],
		[{ x: 9, t: "μετὰ ταῦτα", from: 8 }],
		[{ x: 9, t: "ἐν τῷ ἱερῷ", from: 8 }],
	] },
	{ indent: true, p: "The first prepositional phrase is adverbial because it is a temporal modifier, meaning that it tells us __when__ Jesus found him. The second phrase is adverbial because it is a locative modifier, meaning that it tells us __where__ Jesus found him. Prepositional phrases most often serve these types of adverbial roles." },
	{ indent: true, p: "If our sentence were" },
	{ flow: ["εὑρίσκει ὁ υἱὸς ὁ ζῶν τοῦ ἀνθρώπου αὐτόν"] },
	{ p: "we would write the first line of a flow of this sentence as" },
	{ sf: [
		[{ x: 0, t: "ὁ υἱός" }, { x: 9.7, t: "εὑρίσκει" }, { x: 19.7, t: "αὐτόν." }],
	] },
	{ indent: true, p: "Why did we leave out ὁ ζῶν and τοῦ ἀνθρώπου? Because neither serves the function of subject, verb, direct object, predicate, or indirect object. The first is an attributive participle which __modifies__ ὁ υἱός, and the second is a genitive noun which, like many genitives, functions much like an adjective to __modify__ its leading noun, which in this case is ὁ υἱός. Both are __adjectival__ (not adverbial) modifiers, and therefore require subordination to the noun which governs them. We would demonstrate the subordination as" },
	{ sf: [
		[{ x: 0, t: "~~ὁ υἱός~~" }, { x: 4.8, t: "εὑρίσκει" }, { x: 11.9, t: "αὐτόν" }],
		[{ x: 2, t: "ὁ ζῶν", from: 1 }],
		[{ x: 2, t: "τοῦ ἀνθρώπου", from: 1 }],
	] },
	{ indent: true, p: "If we add the prepositional material of our earlier sentence from John 5:14, our flow becomes" },
	{ sf: [
		[{ x: 0, t: "~~ὁ υἱός~~" }, { x: 15.8, t: "~~εὑρίσκει~~ αὐτόν" }],
		[{ x: 2, t: "ὁ ζῶν", from: 1 }, { x: 17.6, t: "μετὰ ταῦτα", from: 16.6 }],
		[{ x: 2, t: "τοῦ ἀνθρώπου", from: 1 }, { x: 17.6, t: "ἐν τῷ ἱερῷ", from: 16.6 }],
	] },

	{ h: "(2)" },
	{ indent: true, p: "Our explanation of the sentence flow has so far been rather simplistic. For example, there are many other adjectival and adverbial modifiers beside those we have noted above. Two provisional lists (one for adjectives, the other for adverbs) are provided below. Please consult the case synopsis for explanations where they are required." },
	{ marker: "(1)", level: 0, li: "Chief __noun-governors__ are modified by a number of __adjectival__ ideas, each of which can vary at length. The following should be subordinated to nouns in a flow:" },
	{ marker: "a)", level: 1, li: "All attributive adjectives and attributive participles." },
	{ marker: "b)", level: 1, li: "All substantive adjectives and substantive participles: in these instances, the article in the substantive construction represents the governing noun, the adjective or participle the modifier." },
	{ marker: "c)", level: 1, li: "All relative clauses. These clauses most often modify the noun represented by the relative pronoun." },
	{ marker: "d)", level: 1, li: "Many genitives: namely, those which are primarily __descriptive__. According to my synopsis, they include the descriptive genitive, the genitive of possession, the genitive of relationship, the subjective genitive, the objective genitive, and the epexegetical (or appositive) genitive." },
	{ marker: "e)", level: 1, li: "The dative of possession." },
	{ marker: "f)", level: 1, li: "Only those prepositional phrases which take the place of an adjective in an attributive or substantival construction (e.g., τὸ πλήρωμα τὸ ἐν τῷ Χριστῷ)." },
	{ marker: "g)", level: 1, li: "All ablatives (listed in my synopsis) except the ablative of means." },
	{ marker: "(2)", level: 0, li: "Chief __verbal-governors__ are modified by a number of __adverbial__ ideas, which can vary at length. The following should be subordinated to such governors in a flow:" },
	{ marker: "a)", level: 1, li: "Adverbial clauses introduced by temporal and locative adverbs, and especially those introduced by adverbial participles." },
	{ marker: "b)", level: 1, li: "All adverbs and negations (e.g., νῦν, ἤδη, οὐκέτι)." },
	{ marker: "c)", level: 1, li: "The ablative of agency." },
	{ marker: "d)", level: 1, li: "All instrumentals and locatives." },
	{ marker: "e)", level: 1, li: "The datives of advantage, disadvantage, and respect." },
	{ marker: "f)", level: 1, li: "All adverbial genitives: namely, the genitives of time and place, the genitive of respect, the genitive of measure, the genitive absolute, the genitive of advantage, and the genitive of the thing." },
	{ marker: "g)", level: 1, li: "The accusatives of measure and manner (sometimes called the adverbial accusative)." },
	{ marker: "h)", level: 1, li: "Nearly all prepositional phrases, except those which take the place of an adjective in an attributive construction." },
	{ indent: true, p: "Another reason why our discussion has been simplistic is that we have limited it so far to independent clauses. Now we need to consider dependent clauses. They are like independent clauses, since they can take any of the chief noun-governors we listed early on: subject, direct object, indirect object, and predicate. As well, dependent clauses have a chief verbal-governor like that of independent clauses, but with significant differences. For the verbal governor in independent clauses will most often be a finite verb in the indicative mood (although sometimes you will find them in the subjunctive and imperative moods as well). But the verbal governor in dependent clauses will most often be an adverbial participle, an infinitive, or a subjunctive. (Four important exceptions to this are the relative clause, which takes the indicative; ὅτι clauses, which also take the indicative; some temporal clauses, which take the indicative; and some conditional clauses, which also take the indicative.) But you will include the adverbial participle (the verbal governor for some adverbial clauses), the infinitive (the verbal governor for ὥστε clauses, some indirect discourse clauses, and some purpose, causal, and temporal clauses), or the subjunctive (the verbal governor for ἐάν clauses, ἵνα clauses, and various types of independent clauses) among your chief governors when you flow the dependent clause. For instance, in the sentence taken from Luke 20:1" },
	{ flow: ["διδάσκοντος αὐτοῦ τὸν λαὸν ἐν τῷ ἱερῷ ἐπέστησαν οἱ ἀρχιερεῖς"] },
	{ p: "the independent clause (ἐπέστησαν οἱ ἀρχιερεῖς) has a temporal-adverbial modifier for its verb (διδάσκοντος αὐτοῦ), which itself introduces a dependent clause. It should be flowed as follows:" },
	{ sf: [
		[{ x: 0, t: "οἱ ἀρχιερεῖς" }, { x: 9.1, t: "~~ἐπέστησαν~~" }],
		[{ x: 13, t: "~~διδάσκοντος~~ αὐτοῦ τὸν λαόν", from: 10.3 }],
		[{ x: 17.9, t: "ἐν τῷ ἱερῷ", from: 16.6 }],
	] },
	{ indent: true, p: "Note well how the flow starts in the upper left corner and flows downward to the lower right-hand corner. Since the adverbial clause here is dependent, it is subordinated to the main clause, and this subordination is visualized in the direction of its downward flow." },

	{ h: "Fine Points" },
	{ indent: true, p: "Below I have attached a more lengthy flow which may help to visualize what I have attempted in words. And please take long notice of the following fine points:" },
	{ marker: "a)", level: 1, li: "Conjunctions or particles (words which often introduce clauses) should be above and to the left of the clause which they introduce." },
	{ marker: "b)", level: 1, li: "All coordinate, adversative, disjunctive, and inferential clauses (which often begin with καί, δέ, ἀλλά, γάρ, οὖν, etc.) begin far to the left in your flow, since these are types of independent clauses." },
	{ marker: "c)", level: 1, li: "Complementary infinitives and complementary participles should be on the same line with the chief governors of your clause, since they serve to complete the meaning of the action in the verbal governor (e.g., ὁ Ἰησοῦς ἤρξατο λέγειν, Matt 11:7; or ὁ Ἰησοῦς ἐτέλεσεν διατάσσων τοῖς μαθηταῖς, Matt 11:1)." },
	{ marker: "d)", level: 1, li: "Predicate and periphrastic participles should be on the same line with the chief governors of your clause, since the predicate participle functions like any predicate nominative, and since the periphrastic works together with a form of εἰμί to effect a certain tense." },
	{ marker: "e)", level: 1, li: "You will sometimes find __compound__ subjects, __compound__ predicates, __compound__ direct objects, or __compound__ indirect objects in your sentence. Here you must find some neat and consistent way to arrange them according to the rule. Thus the clause from Luke 20:1, ἐπέστησαν οἱ ἀρχιερεῖς καὶ οἱ γραμματεῖς, would be written" },
	{ level: 2, sf: [
		[{ x: 0.6, t: "οἱ ἀρχιερεῖς" }, { x: 8.6, w: 1.4, brace: "top" }],
		[{ x: 0, t: "καί" }, { x: 8.6, w: 1.5, brace: "mid" }, { x: 10.4, t: "ἐπέστησαν" }],
		[{ x: 0.6, t: "οἱ γραμματεῖς" }, { x: 8.6, w: 1.2, brace: "bot" }],
	] },
	{ marker: "f)", level: 1, li: "Remember that genitives which function much like adjectives can attach themselves to any noun, and must therefore be subordinated to that noun. Further, especially in Paul, you will find strings of genitives, so that you will have to subordinate one genitive to another genitive in your flow." },
	{ marker: "g)", level: 1, li: "Articular infinitives, when, as nouns, they are functioning as __subjects__, __objects__, or __predicates__, belong with the other governors on the top line of your flow of a clause." },
	{ marker: "h)", level: 1, li: "__Substantive__ (or noun) clauses (introduced either by the infinitive or by the conjunctions ὅτι, ἵνα) must be displayed according as subjects or direct objects among your chief governors of a clause." },
	{ indent: true, p: "You will encounter other fine points as you work with your flow. Students find it rough going at first, since the flow demands careful grammatical scrutiny of a text, but there comes a point at which the flow will “flow” more as a river than as volcanic lava. Although it painfully forces the student to fine-tune his or her syntactical skills, he or she will nevertheless eventually meander more swiftly through the mountainous and rocky terrain for which Greek is known." },

	{ h: "Sentence Flow: John 13:1–5" },
	{ compact: true, sf: [
		[{ x: 0, t: "^1^ δὲ" }],
		[{ x: 3.7, t: "ὁ Ἰησοῦς… ἠγάπησεν αὐτούς." }],
		[{ x: 7.5, t: "ἀγαπήσας τοὺς ἰδίους" }],
		[{ x: 11.1, t: "τοὺς ἐν τῷ κόσμῳ εἰς τέλος" }],
		[{ x: 7.4, t: "εἰδὼς…ὅτι ἦλθεν … ἡ ὥρα" }],
		[{ x: 19.7, t: "αὐτοῦ" }],
		[{ x: 25.5, t: "ἵνα" }],
		[{ x: 21.9, t: "μεταβῇ" }],
		[{ x: 25.5, t: "ἐκ τοῦ κόσμου τούτου" }],
		[{ x: 25.5, t: "πρὸς τὸν πατέρα," }],
		[{ x: 7.3, t: "Πρὸ…τῆς ἑορτῆς" }],
		[{ x: 14.5, t: "τοῦ πάσχα" }],
		[],
		[{ x: 0, t: "^2–4^ καὶ" }],
		[{ x: 7.4, t: "ἐγείρεται" }],
		[{ x: 11, t: "ἐκ τοῦ δείπνου" }],
		[{ x: 3.6, t: "καὶ" }],
		[{ x: 7.4, t: "τίθησιν τὰ ἱμάτια" }],
		[{ x: 3.6, t: "καὶ" }],
		[{ x: 7.4, t: "διέζωσεν ἑαυτόν·" }],
		[{ x: 11, t: "λαβὼν λέντιον" }],
		[{ x: 9.3, t: "δείπνου γινομένου," }],
		[{ x: 9.3, t: "τοῦ διαβόλου βεβληκότος" }],
		[{ x: 18.2, t: "εἰς τὴν καρδίαν" }],
		[{ x: 25.5, t: "Ἰούδας Σίμωνος Ἰσκαριώτου," }],
		[{ x: 18.1, t: "ἤδη" }],
		[{ x: 18.2, t: "ἵνα παραδοῖ αὐτὸν" }],
		[{ x: 9.3, t: "εἰδὼς" }, { x: 13.3, t: "ὅτι ὁ πατὴρ πάντα ἔδωκεν αὐτῷ" }],
		[{ x: 23.8, t: "εἰς τὰς χεῖρας" }],
		[{ x: 10.9, t: "καὶ" }, { x: 13.5, t: "ὅτι ἐξῆλθεν" }],
		[{ x: 18.2, t: "ἀπὸ θεοῦ" }],
		[{ x: 10.9, t: "καὶ …" }, { x: 15.4, t: "ὑπάγει," }],
		[{ x: 17.3, t: "πρὸς τὸν θεὸν" }],
		[],
		[{ x: 0, t: "^5^" }, { x: 3.7, t: "… βάλλει ὕδωρ" }],
		[{ x: 7.3, t: "εἶτα" }],
		[{ x: 7.3, t: "εἰς τὸν νιπτῆρα" }],
		[{ x: 3.6, t: "καὶ" }],
		[{ x: 5.6, t: "ἤρξατο" }, { x: 11.3, t: "νίπτειν τοὺς πόδας" }],
		[{ x: 16.9, t: "τῶν μαθητῶν" }],
		[{ x: 9.7, t: "καὶ" }],
		[{ x: 10.9, t: "ἐκμάσσειν" }],
		[{ x: 14.5, t: "τῷ λεντίῳ" }],
		[{ x: 18, t: "ᾧ" }],
		[{ x: 18.5, t: "ἦν διεζωσμένος." }],
	] },
];
